[server]
headless = true
port = 8501
baseUrlPath = ""
enableStaticServing = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
fastReruns = true

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#6366f1"
backgroundColor = "#f1f5f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"
